import { getDb } from './db.js';
import type { TranscriptResult, TranscriptSegment } from '../transcripts/types.js';

type CachedTranscriptRow = {
  plain_text: string;
  segments_json: string;
  language: string;
  is_auto_generated: number;
};

export type CachedTranscript = {
  plainText: string;
  segments: TranscriptSegment[];
  language: string;
  isAutoGenerated: boolean;
};

export function getCachedTranscript(platformVideoId: string): CachedTranscript | null {
  const db = getDb();

  const row = db.prepare(`
    SELECT t.plain_text, t.segments_json, t.language, t.is_auto_generated
    FROM transcripts t
    JOIN videos v ON v.id = t.video_id
    WHERE v.platform = 'youtube' AND v.platform_video_id = ?
  `).get(platformVideoId) as CachedTranscriptRow | undefined;

  if (!row) return null;

  return {
    plainText: row.plain_text,
    segments: JSON.parse(row.segments_json) as TranscriptSegment[],
    language: row.language,
    isAutoGenerated: row.is_auto_generated === 1,
  };
}

export function saveTranscript(platformVideoId: string, transcript: Extract<TranscriptResult, { ok: true }>): void {
  const db = getDb();

  const video = db.prepare(`
    SELECT id FROM videos WHERE platform = 'youtube' AND platform_video_id = ?
  `).get(platformVideoId) as { id: number } | undefined;

  if (!video) {
    throw new Error(`Cannot save transcript before video exists: ${platformVideoId}`);
  }

  db.prepare(`
    INSERT INTO transcripts (video_id, source, language, is_auto_generated, plain_text, segments_json)
    VALUES (?, ?, ?, ?, ?, ?)
    ON CONFLICT(video_id)
    DO UPDATE SET
      source = excluded.source,
      language = excluded.language,
      is_auto_generated = excluded.is_auto_generated,
      plain_text = excluded.plain_text,
      segments_json = excluded.segments_json
  `).run(
    video.id,
    transcript.source,
    transcript.language,
    transcript.isAutoGenerated ? 1 : 0,
    transcript.plainText,
    JSON.stringify(transcript.segments),
  );
}
