import { getCachedTranscript, saveTranscript } from '../db/transcript-cache.js';
import { fetchYouTubeTranscript } from './youtube-transcript-provider.js';
import type { TranscriptResult } from './types.js';

export async function resolveTranscript(videoId: string, url: string): Promise<TranscriptResult> {
  const cached = getCachedTranscript(videoId);

  if (cached) {
    return {
      ok: true,
      source: 'cache',
      language: cached.language,
      isAutoGenerated: cached.isAutoGenerated,
      segments: cached.segments,
      plainText: cached.plainText,
    };
  }

  const fetched = await fetchYouTubeTranscript(url);

  if (fetched.ok) {
    saveTranscript(videoId, fetched);
  }

  return fetched;
}
