export type TranscriptSegment = {
  text: string;
  startSeconds: number | null;
  durationSeconds: number | null;
};

export type TranscriptResult =
  | {
      ok: true;
      source: 'cache' | 'youtube-transcript-plus';
      language: string;
      isAutoGenerated: boolean;
      segments: TranscriptSegment[];
      plainText: string;
    }
  | {
      ok: false;
      reason: 'no_transcript' | 'video_unavailable' | 'private_or_restricted' | 'rate_limited' | 'unknown_error';
      error?: string;
    };
