import { fetchTranscript } from 'youtube-transcript-plus';
import { cleanTranscriptText, segmentsToPlainText } from './normalize-transcript.js';
import type { TranscriptResult, TranscriptSegment } from './types.js';

type RawTranscriptSegment = {
  text?: string;
  start?: number | string;
  offset?: number | string;
  duration?: number | string;
  lang?: string;
};

function asNumber(value: unknown): number | null {
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  if (typeof value === 'string') {
    const parsed = Number(value);
    return Number.isFinite(parsed) ? parsed : null;
  }
  return null;
}

function classifyTranscriptError(error: unknown): TranscriptResult {
  const message = error instanceof Error ? error.message : String(error);

  if (/rate|429/i.test(message)) {
    return { ok: false, reason: 'rate_limited', error: message };
  }

  if (/private|restricted|unavailable|disabled/i.test(message)) {
    return { ok: false, reason: 'private_or_restricted', error: message };
  }

  if (/transcript|caption|subtitle/i.test(message)) {
    return { ok: false, reason: 'no_transcript', error: message };
  }

  return { ok: false, reason: 'unknown_error', error: message };
}

export async function fetchYouTubeTranscript(videoIdOrUrl: string): Promise<TranscriptResult> {
  try {
    const raw = (await fetchTranscript(videoIdOrUrl)) as RawTranscriptSegment[];

    const segments: TranscriptSegment[] = raw
      .map((item) => ({
        text: cleanTranscriptText(item.text ?? ''),
        startSeconds: asNumber(item.start ?? item.offset),
        durationSeconds: asNumber(item.duration),
      }))
      .filter((segment) => segment.text.length > 0);

    const plainText = segmentsToPlainText(segments);

    if (!plainText) {
      return { ok: false, reason: 'no_transcript' };
    }

    return {
      ok: true,
      source: 'youtube-transcript-plus',
      language: 'unknown',
      isAutoGenerated: false,
      segments,
      plainText,
    };
  } catch (error) {
    return classifyTranscriptError(error);
  }
}
